/* ATS-One R14 — full publicly-evidenced internal parity overlay */
const R14_VERSION='R14_FULL_PUBLIC_PARITY_1';
window.R14_VERSION=R14_VERSION;

function r14Root(){return document.querySelector('#content .page')||document.querySelector('#content')}
function r14After(html){const r=r14Root();if(r)r.insertAdjacentHTML('beforeend',html)}
function r14Json(v){try{return typeof v==='string'?JSON.parse(v||'{}'):v}catch(_){return {}}}
function r14Table(rows,cols){return `<div class="r14-scroll"><table class="grid"><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr>${(rows||[]).map(r=>`<tr>${cols.map(c=>`<td>${c[2]?c[2](r):esc(r[c[1]]??'')}</td>`).join('')}</tr>`).join('')}</table></div>`}
function r14Empty(rows,msg='No records'){return rows&&rows.length?'':`<div class="r14-empty">${esc(msg)}</div>`}
function r14KV(obj){return `<div class="r14-kv">${Object.entries(obj).map(([k,v])=>`<div><b>${esc(k)}</b><span>${esc(v??'')}</span></div>`).join('')}</div>`}
function r14Create(title,endpoint,fields,after){
  modal(title,`<form id="r14Form"><div class="formgrid">${formFields(fields)}</div></form>`,`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="r14Submit('${endpoint}')">Save</button>`,true);
  window.__r14After=after;
}
async function r14Submit(endpoint){try{const d=fd(document.getElementById('r14Form'));for(const k of Object.keys(d)){if(k.endsWith('_json')){try{d[k]=JSON.parse(d[k]||'{}')}catch(e){return toast(`${k} must be valid JSON`,'err')}}}await api(endpoint,{method:'POST',body:d});closeModal();toast('Saved');if(typeof window.__r14After==='function')await window.__r14After()}catch(e){toast(e.message,'err')}}
async function r14Delete(endpoint,after){if(!confirm('Delete this record?'))return;try{await api(endpoint,{method:'DELETE'});toast('Deleted');if(after)await after()}catch(e){toast(e.message,'err')}}
function r14Section(title,body,actions=''){return `<section class="r14-section"><div class="r14-section-head"><h3>${esc(title)}</h3><div>${actions}</div></div><div class="r14-section-body">${body}</div></section>`}

/* ------------------------------------------------------------------
   SERVER-BACKED CONTACT HOTLISTS — replaces R13 localStorage version
------------------------------------------------------------------- */
pageContactHotlistsR13=async function(){
  const [lists,contacts]=await Promise.all([api('/api/contact-hotlists'),api('/api/contacts')]);
  window.R14_CONTACTS=contacts;
  r13SetHtml(`<div class="page">${head('Contact Hotlists','CRM › Contact Hotlists','<button class="btn primary" onclick="r14NewContactHotlist()">+ New Contact Hotlist</button>')}
  ${panel('Server-backed Contact Hotlists',lists.length?r14Table(lists,[['Name','name'],['Description','description'],['Visibility','visibility'],['Owner','owner_name'],['Members','member_count'],['Actions','id',x=>`<button class="btn small" onclick="r14OpenContactHotlist(${x.id})">Open</button> <button class="btn small danger" onclick="r14DeleteContactHotlist(${x.id})">Delete</button>`]]):'<div class="r14-empty">No contact hotlists yet</div>')}
  ${panel('Contact Directory',r14Table(contacts,[['Name','id',x=>`<a class="link" onclick="go('contact/${x.id}')">${esc((x.first_name||'')+' '+(x.last_name||''))}</a>`],['Company','company_name'],['Title','title'],['Email','email'],['Status','status']]))}</div>`)
}
function r14NewContactHotlist(){r14Create('New Contact Hotlist','/api/contact-hotlists',[{name:'name',label:'Name',required:true},{name:'description',label:'Description',type:'textarea',span:true},{name:'visibility',label:'Visibility',type:'select',options:['Private','Team','Tenant'],value:'Team'}],pageContactHotlistsR13)}
async function r14OpenContactHotlist(id){const h=await api('/api/contact-hotlists/'+id);const contacts=window.R14_CONTACTS||await api('/api/contacts');modal(h.name,`${r14Table(h.members||[],[['Name','contact_id',x=>`${esc(x.first_name+' '+x.last_name)}`],['Title','title'],['Email','email'],['Note','note'],['','contact_id',x=>`<button class="btn small danger" onclick="r14RemoveContactMember(${id},${x.contact_id})">Remove</button>`]])}<hr><div class="field"><label>Add contact</label><select id="r14ContactPick">${contacts.map(c=>`<option value="${c.id}">${esc(c.first_name+' '+c.last_name+' — '+(c.company_name||''))}</option>`).join('')}</select></div>`,`<button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="r14AddContactMember(${id})">Add Contact</button>`,true)}
async function r14AddContactMember(id){await api(`/api/contact-hotlists/${id}/members`,{method:'POST',body:{contact_id:+document.getElementById('r14ContactPick').value}});closeModal();toast('Contact added');await r14OpenContactHotlist(id)}
async function r14RemoveContactMember(hid,cid){await api(`/api/contact-hotlists/${hid}/members/${cid}`,{method:'DELETE'});closeModal();toast('Contact removed');await r14OpenContactHotlist(hid)}
async function r14DeleteContactHotlist(id){if(!confirm('Delete contact hotlist?'))return;await api('/api/contact-hotlists/'+id,{method:'DELETE'});toast('Deleted');pageContactHotlistsR13()}

/* ------------------------------------------------------------------
   ENTERPRISE CANDIDATE RECORD
------------------------------------------------------------------- */
async function pageR14CandidateEnterprise(){
 const cs=await api('/api/candidates?include_archived=1');
 r13SetHtml(`<div class="page">${head('Candidate Enterprise Operations','Talent Management › Enterprise Record')}${panel('Candidate',`<select id="r14CandPick" onchange="r14CandidateEnterpriseLoad(+this.value)"><option value="">Select candidate</option>${cs.map(c=>`<option value="${c.id}">${esc(c.first_name+' '+c.last_name+' — '+(c.current_title||''))}</option>`).join('')}</select><div id="r14-cand-enterprise"></div>`)}</div>`)
}
async function r14CandidateEnterpriseLoad(cid){if(!cid)return;const [eeo,hr,bg,privacy,dups]=await Promise.all([api('/api/r14/candidate-eeo'),api('/api/r14/candidate-hr'),api('/api/r14/candidate-background'),api('/api/r14/candidate-privacy'),api('/api/candidates/duplicates?candidate_id='+cid)]);const f=x=>Number(x.candidate_id)===Number(cid);document.getElementById('r14-cand-enterprise').innerHTML=`
 ${r14Section('Duplicate / Merge Review',dups.length?r14Table(dups,[['Candidate','id',x=>`${esc(x.first_name+' '+x.last_name)}`],['Email','email'],['Phone','phone'],['Score','duplicate_score'],['Action','id',x=>`<button class="btn small danger" onclick="r14MergeCandidate(${x.id},${cid})">Merge into selected</button>`]]):'<div class="r14-empty">No likely duplicates</div>')}
 ${r14Section('EEO / Voluntary Data',r14Table(eeo.filter(f),[['Gender','gender'],['Ethnicity','ethnicity'],['Veteran','veteran_status'],['Disability','disability_status'],['Consent','consent_at']]),`<button class="btn small" onclick="r14Create('EEO Record','/api/r14/candidate-eeo',[{name:'candidate_id',label:'Candidate ID',type:'number',value:${cid}},{name:'gender',label:'Gender'},{name:'ethnicity',label:'Ethnicity'},{name:'veteran_status',label:'Veteran Status'},{name:'disability_status',label:'Disability Status'},{name:'consent_at',label:'Consent At'}],()=>r14CandidateEnterpriseLoad(${cid}))">+ EEO</button>`)}
 ${r14Section('HR Records',r14Table(hr.filter(f),[['Employee #','employee_no'],['Type','employment_type'],['Department','department'],['Hire','hire_date'],['Termination','termination_date']]),`<button class="btn small" onclick="r14Create('HR Record','/api/r14/candidate-hr',[{name:'candidate_id',label:'Candidate ID',type:'number',value:${cid}},{name:'employee_no',label:'Employee #'},{name:'employment_type',label:'Employment Type'},{name:'department',label:'Department'},{name:'manager',label:'Manager'},{name:'hire_date',label:'Hire Date',type:'date'}],()=>r14CandidateEnterpriseLoad(${cid}))">+ HR</button>`)}
 ${r14Section('Background Cases',r14Table(bg.filter(f),[['Provider','provider'],['Package','package_name'],['Status','status'],['External ID','external_id'],['Completed','completed_at']]),`<button class="btn small" onclick="r14Create('Background Case','/api/r14/candidate-background',[{name:'candidate_id',label:'Candidate ID',type:'number',value:${cid}},{name:'provider',label:'Provider'},{name:'package_name',label:'Package'},{name:'status',label:'Status'}],()=>r14CandidateEnterpriseLoad(${cid}))">+ Case</button>`)}
 ${r14Section('Privacy / Redaction History',r14Table(privacy.filter(f),[['Action','action_type'],['Status','status'],['Date','completed_at'],['Note','note']]),ME?.role==='admin'?`<button class="btn small danger" onclick="r14RedactCandidate(${cid})">Redact Candidate PII</button>`:'')}`
}
async function r14MergeCandidate(source,target){if(!confirm(`Merge candidate ${source} into ${target}? Source will be archived.`))return;await api('/api/candidates/merge',{method:'POST',body:{source_candidate_id:source,target_candidate_id:target}});toast('Candidate merged');r14CandidateEnterpriseLoad(target)}
async function r14RedactCandidate(cid){const note=prompt('Privacy request / legal basis note:');if(note===null)return;if(!confirm('This redacts candidate PII. Continue?'))return;await api('/api/candidates/redact',{method:'POST',body:{candidate_id:cid,note}});toast('Candidate PII redacted');r14CandidateEnterpriseLoad(cid)}

/* ------------------------------------------------------------------
   JOB OPERATIONS
------------------------------------------------------------------- */
async function pageR14JobOps(){const [cats,alerts,hist]=await Promise.all([api('/api/r14/job-catalogs'),api('/api/r14/job-alerts'),api('/api/r14/job-status-history')]);r13SetHtml(`<div class="page">${head('Job Enterprise Operations','Job Management › Catalogs / Alerts / History')}${r14Section('Job Catalogs',r14Table(cats,[['Name','name'],['Profession','profession'],['Specialty','specialty'],['Active','active']]),`<button class="btn small" onclick="r14Create('Job Catalog','/api/r14/job-catalogs',[{name:'name',label:'Name'},{name:'profession',label:'Profession'},{name:'specialty',label:'Specialty'},{name:'description',label:'Description',type:'textarea'}],pageR14JobOps)">+ Catalog</button>`)}${r14Section('Job Alerts',r14Table(alerts,[['Name','name'],['Channel','channel'],['Frequency','frequency'],['Active','active']]),`<button class="btn small" onclick="r14Create('Job Alert','/api/r14/job-alerts',[{name:'name',label:'Name'},{name:'criteria_json',label:'Criteria JSON',type:'textarea',value:'{}'},{name:'channel',label:'Channel',value:'Email'},{name:'frequency',label:'Frequency',value:'Daily'}],pageR14JobOps)">+ Alert</button>`)}${r14Section('Job Status History',r14Table(hist,[['Job ID','job_id'],['From','from_status'],['To','to_status'],['Note','note'],['Date','created_at']]))}</div>`)}

/* ------------------------------------------------------------------
   STARTS / ONBOARDING / COMPLIANCE
------------------------------------------------------------------- */
async function pageR14Starts(){const [starts,events]=await Promise.all([api('/api/starts'),api('/api/r14/start-events')]);r13SetHtml(`<div class="page">${head('Starts & Terminations','Workforce › Starts')}${r14Section('Starts',r14Table(starts,[['Candidate','first_name',x=>esc((x.first_name||'')+' '+(x.last_name||''))],['Job','job_title'],['Start','start_date'],['Status','status'],['Reason','cancellation_reason']]))}${r14Section('Start / Termination History',r14Table(events,[['Start ID','start_id'],['Event','event_type'],['From','from_status'],['To','to_status'],['Effective','effective_date'],['Reason','reason']]),`<button class="btn small" onclick="r14Create('Start Event','/api/r14/start-events',[{name:'start_id',label:'Start ID',type:'number'},{name:'event_type',label:'Event Type',value:'Status Change'},{name:'from_status',label:'From'},{name:'to_status',label:'To'},{name:'effective_date',label:'Effective Date',type:'date'},{name:'reason',label:'Reason',type:'textarea'}],pageR14Starts)">+ Event</button>`)}</div>`)}
async function pageR14OnboardingCompliance(){const [rules,esign,verify,bg]=await Promise.all([api('/api/r14/onboarding-rules'),api('/api/r14/esign-envelopes'),api('/api/r14/employment-verifications'),api('/api/r14/candidate-background')]);r13SetHtml(`<div class="page">${head('Onboarding Compliance Engine','Onboarding › Rules / Signature / Verification')}${r14Section('Conditional Onboarding Rules',r14Table(rules,[['Name','name'],['Client','client_id'],['State','state'],['Profession','profession'],['Priority','priority'],['Active','active']]),`<button class="btn small" onclick="r14Create('Onboarding Rule','/api/r14/onboarding-rules',[{name:'name',label:'Name'},{name:'client_id',label:'Client ID',type:'number'},{name:'profession',label:'Profession'},{name:'state',label:'State'},{name:'country',label:'Country'},{name:'tax_category',label:'Tax Category'},{name:'condition_json',label:'Condition JSON',type:'textarea',value:'{}'},{name:'template_id',label:'Template ID',type:'number'},{name:'priority',label:'Priority',type:'number',value:100}],pageR14OnboardingCompliance)">+ Rule</button>`)}${r14Section('E-Sign Envelopes',r14Table(esign,[['Candidate','candidate_id'],['Provider','provider'],['Subject','subject'],['Status','status'],['Signed','signed_at']]))}${r14Section('Employment / Work Verification',r14Table(verify,[['Candidate','candidate_id'],['Provider','provider'],['Case','case_type'],['Status','status'],['Result','result']]))}${r14Section('Background Cases',r14Table(bg,[['Candidate','candidate_id'],['Provider','provider'],['Package','package_name'],['Status','status']]))}</div>`)}

/* ------------------------------------------------------------------
   TIME / FINANCE
------------------------------------------------------------------- */
async function pageR14TimeOps(){const [rules,adj,locks]=await Promise.all([api('/api/r14/time-rules'),api('/api/r14/timesheet-adjustments'),api('/api/r14/time-locks')]);r13SetHtml(`<div class="page">${head('Time & Attendance Rules','Back Office › Time Rules')}${r14Section('Time Rules',r14Table(rules,[['Name','name'],['Rule Type','rule_type'],['State','state'],['Threshold','threshold'],['Multiplier','multiplier'],['Active','active']]),`<button class="btn small" onclick="r14Create('Time Rule','/api/r14/time-rules',[{name:'name',label:'Name'},{name:'rule_type',label:'Rule Type',value:'Daily OT'},{name:'state',label:'State'},{name:'country',label:'Country'},{name:'threshold',label:'Threshold',type:'number'},{name:'multiplier',label:'Multiplier',type:'number',value:1.5},{name:'config_json',label:'Config JSON',type:'textarea',value:'{}'}],pageR14TimeOps)">+ Rule</button>`)}${r14Section('Timesheet Adjustments',r14Table(adj,[['Timesheet','timesheet_id'],['Reason','reason'],['Status','status'],['Requested','requested_at'],['Acted','acted_at']]))}${r14Section('Period Locks',r14Table(locks,[['From','period_start'],['To','period_end'],['Scope','scope_type'],['Locked','locked'],['Reason','reason']]),`<button class="btn small" onclick="r14Create('Period Lock','/api/r14/time-locks',[{name:'period_start',label:'From',type:'date'},{name:'period_end',label:'To',type:'date'},{name:'scope_type',label:'Scope',value:'Tenant'},{name:'reason',label:'Reason'}],pageR14TimeOps)">+ Lock</button>`)}</div>`)}
async function pageR14FinancialOps(){const [sows,ms,pb,sal,bill,ov,pd,st,wc]=await Promise.all(['/api/r14/sows','/api/r14/milestones','/api/r14/payroll-batches','/api/r14/salary-records','/api/r14/billing-records','/api/r14/overheads','/api/r14/per-diems','/api/r14/stipends','/api/r14/workers-comp'].map(x=>api(x)));r13SetHtml(`<div class="page">${head('Enterprise Financial Operations','Finance › SOW / Payroll / Costing')}${r14Section('Statements of Work',r14Table(sows,[['SOW #','sow_no'],['Name','name'],['Company','company_id'],['Status','status'],['Budget','budget',x=>money(x.budget)],['Billed','billed',x=>money(x.billed)]]),`<button class="btn small" onclick="r14Create('SOW','/api/r14/sows',[{name:'sow_no',label:'SOW #'},{name:'company_id',label:'Company ID',type:'number'},{name:'name',label:'Name'},{name:'status',label:'Status',value:'Draft'},{name:'budget',label:'Budget',type:'number'},{name:'currency',label:'Currency',value:'USD'}],pageR14FinancialOps)">+ SOW</button>`)}${r14Section('Milestones',r14Table(ms,[['SOW','sow_id'],['Name','name'],['Due','due_date'],['Amount','amount',x=>money(x.amount)],['Status','status']]))}${r14Section('Payroll Batches',r14Table(pb,[['Batch','batch_no'],['Period','period_start',x=>`${esc(x.period_start||'')} — ${esc(x.period_end||'')}`],['Status','status'],['Gross','gross_pay',x=>money(x.gross_pay)],['Net','net_pay',x=>money(x.net_pay)] ]))}${r14Section('Salary / Pay Records',r14Table(sal,[['Candidate','candidate_id'],['Assignment','assignment_id'],['Effective','effective_date'],['Type','pay_type'],['Regular','regular_rate',x=>money(x.regular_rate)],['OT','ot_rate',x=>money(x.ot_rate)]]))}${r14Section('Billing Records',r14Table(bill,[['Assignment','assignment_id'],['Date','work_date'],['Units','units'],['Rate','rate',x=>money(x.rate)],['Amount','amount',x=>money(x.amount)],['Status','status']]))}${r14Section('Cost Rules',r14Table([...ov.map(x=>({...x,_kind:'Overhead'})),...pd.map(x=>({...x,_kind:'Per Diem'})),...st.map(x=>({...x,_kind:'Stipend'})),...wc.map(x=>({...x,_kind:'Workers Comp'}))],[['Kind','_kind'],['Name/Code','name',x=>x.name||x.code],['Amount/Rate','value',x=>x.value??x.amount??x.rate],['State/Location','state',x=>x.state||x.location||''],['Active','active']]))}</div>`)}

/* ------------------------------------------------------------------
   COMMUNICATION / REPORTS / WORKFLOW
------------------------------------------------------------------- */
async function pageR14Comms(){const [threads,camps]=await Promise.all([api('/api/r14/threads'),api('/api/r14/campaigns')]);r13SetHtml(`<div class="page">${head('Communication Hub','Communication › Threads / Campaigns')}${r14Section('Conversation Threads',r14Table(threads,[['Subject','subject'],['Entity','entity_type'],['ID','entity_id'],['Status','status'],['Updated','updated_at']]),`<button class="btn small" onclick="r14Create('Thread','/api/r14/threads',[{name:'entity_type',label:'Entity Type',value:'candidate'},{name:'entity_id',label:'Entity ID',type:'number'},{name:'subject',label:'Subject'},{name:'status',label:'Status',value:'Open'}],pageR14Comms)">+ Thread</button>`)}${r14Section('Campaigns',r14Table(camps,[['Name','name'],['Channel','channel'],['Subject','subject'],['Status','status'],['Scheduled','scheduled_at'],['Sent','sent_at']]),`<button class="btn small" onclick="r14Create('Campaign','/api/r14/campaigns',[{name:'name',label:'Name'},{name:'channel',label:'Channel',value:'Email'},{name:'subject',label:'Subject'},{name:'body',label:'Body',type:'textarea',span:true},{name:'status',label:'Status',value:'Draft'},{name:'scheduled_at',label:'Scheduled At'}],pageR14Comms)">+ Campaign</button>`)}</div>`)}
async function pageR14ReportBuilder(){const [defs,sched,dashes]=await Promise.all([api('/api/r14/report-builders'),api('/api/r14/report-schedules'),api('/api/r14/dashboards')]);r13SetHtml(`<div class="page">${head('Report & Dashboard Builder','Reporting › Builder / Scheduler')}${r14Section('Custom Reports',r14Table(defs,[['Name','name'],['Entity','entity_type'],['Shared','is_shared'],['Actions','id',x=>`<button class="btn small" onclick="r14RunReport(${x.id})">Run</button>`]]),`<button class="btn small" onclick="r14Create('Custom Report','/api/r14/report-builders',[{name:'name',label:'Name'},{name:'entity_type',label:'Entity',type:'select',options:['candidates','jobs','submissions','assignments','timesheets','expenses','invoices','companies','contacts']},{name:'columns_json',label:'Columns JSON',type:'textarea',value:'[]'},{name:'filters_json',label:'Filters JSON',type:'textarea',value:'{}'},{name:'is_shared',label:'Shared (0/1)',type:'number',value:0}],pageR14ReportBuilder)">+ Report</button>`)}${r14Section('Schedules',r14Table(sched,[['Report','report_id'],['Frequency','frequency'],['Recipients','recipients'],['Format','format'],['Next','next_run_at'],['Active','active']]))}${r14Section('Dashboards',r14Table(dashes,[['Name','name'],['Owner','owner_user_id'],['Shared','is_shared'],['Updated','updated_at']]),`<button class="btn small" onclick="r14Create('Dashboard','/api/r14/dashboards',[{name:'name',label:'Name'},{name:'is_shared',label:'Shared (0/1)',type:'number',value:0},{name:'layout_json',label:'Layout JSON',type:'textarea',value:'{}'}],pageR14ReportBuilder)">+ Dashboard</button>`)}</div>`)}
async function r14RunReport(id){const r=await api('/api/report-builder/run?id='+id);modal('Report Result',`<div class="r14-scroll"><table class="grid"><tr>${r.columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>${r.rows.map(row=>`<tr>${r.columns.map(c=>`<td>${esc(row[c]??'')}</td>`).join('')}</tr>`).join('')}</table></div><p>${r.count} row(s)</p>`,`<button class="btn" onclick="closeModal()">Close</button>`,true)}
async function pageR14Workflow(){const [wf,runs]=await Promise.all([api('/api/r14/workflows'),api('/api/r14/workflow-runs')]);r13SetHtml(`<div class="page">${head('Workflow Studio','Admin › Workflow Automation')}${r14Section('Definitions',r14Table(wf,[['Name','name'],['Trigger','trigger_name'],['Entity','entity_type'],['Version','version'],['Active','active'],['Action','id',x=>`<button class="btn small" onclick="r14RunWorkflow(${x.id})">Run Test</button>`]]),`<button class="btn small" onclick="r14Create('Workflow','/api/r14/workflows',[{name:'name',label:'Name'},{name:'trigger_name',label:'Trigger',value:'manual'},{name:'entity_type',label:'Entity Type',value:'candidate'},{name:'definition_json',label:'Definition JSON',type:'textarea',value:'{"steps":[]}'},{name:'active',label:'Active (0/1)',type:'number',value:1}],pageR14Workflow)">+ Workflow</button>`)}${r14Section('Runs',r14Table(runs,[['Workflow','workflow_id'],['Entity','entity_type'],['Entity ID','entity_id'],['Status','status'],['Started','started_at'],['Finished','finished_at'],['Error','error']]))}</div>`)}
async function r14RunWorkflow(id){await api('/api/workflows/run',{method:'POST',body:{workflow_id:id,context:{mode:'manual-test'}}});toast('Workflow executed');pageR14Workflow()}

/* ------------------------------------------------------------------
   SUPPLIER / ORG / AUTH / EXTERNAL
------------------------------------------------------------------- */
async function pageR14SupplierGov(){const [c,s,k]=await Promise.all([api('/api/r14/supplier-contracts'),api('/api/r14/supplier-scorecards'),api('/api/r14/supplier-compliance')]);r13SetHtml(`<div class="page">${head('Supplier Governance','VMS / Suppliers › Governance')}${r14Section('Contracts',r14Table(c,[['Supplier','supplier_id'],['Contract','contract_no'],['From','start_date'],['To','end_date'],['Status','status']]))}${r14Section('Scorecards',r14Table(s,[['Supplier','supplier_id'],['Period','period_start',x=>`${esc(x.period_start||'')} — ${esc(x.period_end||'')}`],['Subs','submittals'],['Interviews','interviews'],['Hires','hires'],['Quality','quality_score'],['SLA','sla_score']]))}${r14Section('Compliance',r14Table(k,[['Supplier','supplier_id'],['Requirement','requirement'],['Status','status'],['Expiry','expiry_date']]))}</div>`)}
async function pageR14Org(){const [d,g,m,goals]=await Promise.all([api('/api/r14/divisions'),api('/api/r14/user-groups'),api('/api/r14/group-members'),api('/api/r14/user-goals')]);r13SetHtml(`<div class="page">${head('Organization & Goals','Admin › Divisions / Groups')}${r14Section('Divisions',r14Table(d,[['Name','name'],['Code','code'],['Parent','parent_id'],['Status','status']]),`<button class="btn small" onclick="r14Create('Division','/api/r14/divisions',[{name:'name',label:'Name'},{name:'code',label:'Code'},{name:'parent_id',label:'Parent ID',type:'number'},{name:'status',label:'Status',value:'Active'}],pageR14Org)">+ Division</button>`)}${r14Section('Groups',r14Table(g,[['Name','name'],['Description','description'],['Division','division_id']]))}${r14Section('Memberships',r14Table(m,[['Group','group_id'],['User','user_id'],['Role','group_role']]))}${r14Section('User Goals',r14Table(goals,[['User','user_id'],['Type','goal_type'],['Target','target'],['Actual','actual'],['Status','status']]))}</div>`)}
async function pageR14Security(){const [sessions,mfa,sso]=await Promise.all([api('/api/auth/sessions'),api('/api/auth/mfa'),ME?.role==='admin'?api('/api/r14/sso-configs'):Promise.resolve([])]);r13SetHtml(`<div class="page">${head('Security Center','Admin › Authentication / Sessions')}${r14Section('Current Sessions',r14Table(sessions,[['Session','id'],['Created','created_at'],['Expires','expires_at'],['Action','id',x=>`<button class="btn small danger" onclick="r14Delete('/api/auth/sessions/${x.id}',pageR14Security)">Revoke</button>`]]))}${r14Section('Multi-Factor Authentication',r14KV({Enabled:mfa.enabled?'Yes':'No',Verified:mfa.verified_at||''}),mfa.enabled?'':`<button class="btn small" onclick="r14MfaSetup()">Set up TOTP MFA</button>`)}${ME?.role==='admin'?r14Section('SSO Configurations',r14Table(sso,[['Name','name'],['Protocol','protocol'],['Domain','domain'],['Issuer','issuer'],['Enabled','enabled']]),`<button class="btn small" onclick="r14Create('SSO Configuration','/api/r14/sso-configs',[{name:'name',label:'Name'},{name:'protocol',label:'Protocol',value:'SAML'},{name:'issuer',label:'Issuer'},{name:'login_url',label:'Login URL'},{name:'certificate_fingerprint',label:'Certificate Fingerprint'},{name:'domain',label:'Domain'},{name:'enabled',label:'Enabled (0/1)',type:'number',value:0}],pageR14Security)">+ SSO Config</button>`):''}</div>`)}
async function r14MfaSetup(){const d=await api('/api/auth/mfa/setup',{method:'POST',body:{}});modal('TOTP MFA Setup',`<p>Add this secret to your authenticator app:</p><pre>${esc(d.secret)}</pre><p class="subtle">${esc(d.otpauth_uri)}</p><div class="field"><label>6-digit code</label><input id="r14MfaCode"></div>`,`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="r14MfaVerify()">Verify</button>`)}
async function r14MfaVerify(){await api('/api/auth/mfa/verify',{method:'POST',body:{code:document.getElementById('r14MfaCode').value}});closeModal();toast('MFA enabled');pageR14Security()}
async function pageR14External(){const rows=await api('/api/r14/external-gateways');r13SetHtml(`<div class="page">${head('External Integration Gates','Admin › Vendor Connections')}${panel('Contract / Credential Bound Integrations',r14Table(rows,[['Provider','provider'],['Category','category'],['Status','status'],['Credential Ref','credential_ref'],['Last Test','last_test_at'],['Last Error','last_error']]))}<div class="callout warn"><b>Truth gate:</b> adapters and data contracts are present, but a provider is not "Connected" until real credentials/contracts are supplied and a live provider test succeeds.</div></div>`)}

/* ------------------------------------------------------------------
   ROLE PORTAL EXTENSIONS
------------------------------------------------------------------- */
async function r14EnhancePortal(base){
 if(base==='candidatePortal' && ME?.candidate_id){const [eeo,verify]=await Promise.all([api('/api/r14/candidate-eeo').catch(()=>[]),api('/api/r14/employment-verifications').catch(()=>[])]);r14After(r14Section('Profile & Compliance Self-Service',`<p>Profile edits, availability, documents, applications and compliance records use the same tenant-safe candidate record.</p>${r14Table((verify||[]).filter(x=>Number(x.candidate_id)===Number(ME.candidate_id)),[['Verification','case_type'],['Provider','provider'],['Status','status'],['Result','result']])}`))}
 if(base==='clientPortal'){const req=await api('/api/r14/requisition-requests').catch(()=>[]);r14After(r14Section('Requisition Requests',r14Table(req,[['Title','title'],['Location','location'],['Openings','openings'],['Status','status'],['Requested','requested_at']]),`<button class="btn small" onclick="r14Create('Request Requisition','/api/r14/requisition-requests',[{name:'title',label:'Title'},{name:'description',label:'Description',type:'textarea'},{name:'location',label:'Location'},{name:'openings',label:'Openings',type:'number',value:1}],()=>route('clientPortal'))">+ Requisition Request</button>`))}
 if(base==='workerPortal'){const [pto,pay]=await Promise.all([api('/api/r14/pto-requests').catch(()=>[]),api('/api/r14/pay-statements').catch(()=>[])]);r14After(r14Section('PTO / Leave Requests',r14Table(pto,[['From','start_date'],['To','end_date'],['Hours','hours'],['Reason','reason'],['Status','status']]),`<button class="btn small" onclick="r14Create('PTO Request','/api/r14/pto-requests',[{name:'assignment_id',label:'Assignment ID',type:'number'},{name:'start_date',label:'From',type:'date'},{name:'end_date',label:'To',type:'date'},{name:'hours',label:'Hours',type:'number'},{name:'reason',label:'Reason'}],()=>route('workerPortal'))">+ PTO Request</button>`)+r14Section('Pay Statements',r14Table(pay,[['Period','period_start',x=>`${esc(x.period_start||'')} — ${esc(x.period_end||'')}`],['Gross','gross',x=>money(x.gross)],['Deductions','deductions',x=>money(x.deductions)],['Net','net',x=>money(x.net)],['Currency','currency']]))) }
 if(base==='supplierPortal'){const [c,s,k]=await Promise.all([api('/api/r14/supplier-contracts').catch(()=>[]),api('/api/r14/supplier-scorecards').catch(()=>[]),api('/api/r14/supplier-compliance').catch(()=>[])]);r14After(r14Section('Supplier Governance',`${r14Table(c,[['Contract','contract_no'],['Start','start_date'],['End','end_date'],['Status','status']])}${r14Table(s,[['Quality','quality_score'],['SLA','sla_score'],['Hires','hires']])}${r14Table(k,[['Requirement','requirement'],['Status','status'],['Expiry','expiry_date']])}`))}
}

/* ------------------------------------------------------------------
   MENU + ROUTE INTEGRATION
------------------------------------------------------------------- */
const R14_PREV_MENU=pageMenu;
pageMenu=function(){R14_PREV_MENU();const launcher=document.querySelector('.launcher');if(!launcher)return;launcher.insertAdjacentHTML('beforeend',`<div class="module-card r14-card"><h3>Enterprise Parity</h3><div class="module-links">
 ${[['Candidate Enterprise','r14Candidate'],['Job Operations','r14Jobs'],['Starts & Terminations','r14Starts'],['Onboarding Compliance','r14Onboarding'],['Time Rules','r14Time'],['Financial Operations','r14Finance'],['Communication Hub','r14Comms'],['Report Builder','r14Reports'],['Workflow Studio','r14Workflow'],['Supplier Governance','r14Supplier'],['Organization','r14Org'],['Security Center','r14Security'],['External Gates','r14External']].map(x=>`<div class="module-link" onclick="go('${x[1]}')"><span class="module-ico">◆</span><span class="module-name">${x[0]}</span></div>`).join('')}
 </div></div>`)};

const R14_PREV_ROUTE=route;
route=async function(r){
 const base=(r||'').split('/')[0];
 const map={r14Candidate:pageR14CandidateEnterprise,r14Jobs:pageR14JobOps,r14Starts:pageR14Starts,r14Onboarding:pageR14OnboardingCompliance,r14Time:pageR14TimeOps,r14Finance:pageR14FinancialOps,r14Comms:pageR14Comms,r14Reports:pageR14ReportBuilder,r14Workflow:pageR14Workflow,r14Supplier:pageR14SupplierGov,r14Org:pageR14Org,r14Security:pageR14Security,r14External:pageR14External};
 if(map[base]){CURRENT=r;document.querySelectorAll('.navitem').forEach(n=>n.classList.toggle('active',n.dataset.route===r));const c=document.getElementById('content');if(c)c.innerHTML='<div class="page"><div class="panel"><div class="panel-body">Loading…</div></div></div>';try{await map[base]()}catch(e){if(c)c.innerHTML=`<div class="page"><div class="panel"><div class="panel-body"><b>Unable to load page.</b><br>${esc(e.message)}</div></div></div>`}return}
 await R14_PREV_ROUTE(r);await r14EnhancePortal(base);
};

/* PWA installable mobile-web foundation. Native store apps still require store/provider accounts. */
try{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}catch(_){}

/* MFA-capable login UI; existing accounts without MFA continue unchanged. */
function r14PatchLoginForm(){const f=document.getElementById('loginForm');if(!f||f.elements.mfa_code)return;const pw=f.elements.password?.closest('.field');if(pw)pw.insertAdjacentHTML('afterend','<div class="field"><label>MFA Code (only if enabled)</label><input name="mfa_code" inputmode="numeric" autocomplete="one-time-code" placeholder="6-digit authenticator code"></div>')}
try{r14PatchLoginForm()}catch(_){}
const R14_ORIG_RENDER_LOGIN=renderLogin;
renderLogin=function(){R14_ORIG_RENDER_LOGIN();r14PatchLoginForm()};
const R14_ORIG_QUICK_LOGIN=quickLogin;
quickLogin=async function(email,password){try{await api('/api/login',{method:'POST',body:{email,password}});await boot()}catch(e){if(String(e.message).toLowerCase().includes('mfa')){const code=prompt('MFA code for this account:');if(!code)return;try{await api('/api/login',{method:'POST',body:{email,password,mfa_code:code}});await boot()}catch(e2){toast(e2.message,'err')}}else toast(e.message,'err')}};
